openapi: 3.0.1
info:
  title: AuthAPI
  description: API Definition of AuthAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/api/auth
paths:
  /:
    get:
      responses:
        default:
          description: Default response
