openapi: 3.0.1
info:
  title: DeliveryAPI
  description: API Definition of DeliveryAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/api/delivery
paths:
  /:
    get:
      responses:
        default:
          description: Default response
