openapi: 3.0.1
info:
  title: PaymentAPI
  description: API Definition of PaymentAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/api/payment
paths:
  /:
    post:
      responses:
        default:
          description: Default response
  /buyer/{product}:
    get:
      parameters:
      - name: product
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
    post:
      parameters:
      - name: product
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
