---
key: "ProductAPI-1.0.0"
name : "ProductAPI"
displayName : "ProductAPI"
description: "Sample API"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/api/product"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
apiId : "null"
