openapi: 3.0.1
info:
  title: ProductAPI
  description: API Definition of ProductAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/api/product
paths:
  /:
    get:
      responses:
        default:
          description: Default response
